// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtRT91Vm5EVnyrY7c5_p1CF7kIjdSUEFY',
    appId: '1:6308610076:web:b4ef31dce992bb32a0dfd9',
    messagingSenderId: '6308610076',
    projectId: 'restate-3647a',
    authDomain: 'restate-3647a.firebaseapp.com',
    storageBucket: 'restate-3647a.appspot.com',
    measurementId: 'G-TTQ8EJKZX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC8SEG04ZbT3tCKMwauYiSjraXeeXIbCM',
    appId: '1:6308610076:android:994f793e5b7ca2d0a0dfd9',
    messagingSenderId: '6308610076',
    projectId: 'restate-3647a',
    storageBucket: 'restate-3647a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrfQjBaR9AGW24Cp_qKdph2wHrZLnApWI',
    appId: '1:6308610076:ios:1ba473d69ecdfca2a0dfd9',
    messagingSenderId: '6308610076',
    projectId: 'restate-3647a',
    storageBucket: 'restate-3647a.appspot.com',
    iosBundleId: 'com.example.restate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrfQjBaR9AGW24Cp_qKdph2wHrZLnApWI',
    appId: '1:6308610076:ios:d80d0abafe584a2ba0dfd9',
    messagingSenderId: '6308610076',
    projectId: 'restate-3647a',
    storageBucket: 'restate-3647a.appspot.com',
    iosBundleId: 'com.example.restate.RunnerTests',
  );
}
