import 'package:flutter/material.dart';

class HelpSection extends StatefulWidget {
  @override
  _HelpSectionState createState() => _HelpSectionState();
}

class _HelpSectionState extends State<HelpSection> {
  @override
  Widget build(BuildContext context) {
    final double width = MediaQuery.of(context).size.width;
    return Scaffold(
        appBar: AppBar(
          title: Text('Help'),
          backgroundColor: Colors.amber,
        ),
        body: Column(
          children: [
            Align(
              alignment: Alignment.centerLeft,
              child: Padding(
                padding: EdgeInsets.only(left: 20.0, top: 15.0, bottom: 15.0),
                child: Text(
                  "What issue are you facing?",
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                ),
              ),
            ),
            Divider(),
            DropdownMenu(
                inputDecorationTheme: InputDecorationTheme(
                  border: OutlineInputBorder(
                    borderSide: BorderSide.none,
                  ),
                ),
                label: Text("How to upload Machinery?"),
                width: width * 0.95,
                dropdownMenuEntries: <DropdownMenuEntry>[
                  DropdownMenuEntry(
                      value: 1,
                      label:
                          "by clicking on the the +new button in the home screen you will be redirected to upload machinery form fill the details and upload the machinery."),
                ]),
            Divider(),
            DropdownMenu(
                inputDecorationTheme: InputDecorationTheme(
                  border: OutlineInputBorder(
                    borderSide: BorderSide.none,
                  ),
                ),
                label:
                    Text("How to check my orders i have completed or ongoing?"),
                width: width * 0.95,
                dropdownMenuEntries: <DropdownMenuEntry>[
                  DropdownMenuEntry(
                      value: 1,
                      label:
                          "Go to yourorders page in menu, Here you can check all the orders you have completed or ongoing."),
                ]),
            Divider(),
            DropdownMenu(
                label: Text("How to check my inventory?"),
                width: width * 0.95,
                inputDecorationTheme: InputDecorationTheme(
                  border: OutlineInputBorder(
                    borderSide: BorderSide.none,
                  ),
                ),
                dropdownMenuEntries: const <DropdownMenuEntry>[
                  DropdownMenuEntry(
                      value: 1,
                      label:
                          "Go to inventory page, Here  you can check all the machinery you have in your inventory, You can also edit or delete the machinery in your inventory in this page."),
                ]),
            Divider(),
            DropdownMenu(
                label: Text("How to check my revenue?"),
                width: width * 0.95,
                inputDecorationTheme: InputDecorationTheme(
                  border: OutlineInputBorder(
                    borderSide: BorderSide.none,
                  ),
                ),
                dropdownMenuEntries: const <DropdownMenuEntry>[
                  DropdownMenuEntry(
                      value: 1,
                      label:
                          "Go to revenue page in the Menu. Here you can check all the revenue generated by you."),
                ]),
            Divider(),
          ],
        ));
  }
}
